"""Subclass of UIFrame_Config, which is generated by wxFormBuilder."""

import wx
import ui

# Implementing UIFrame_Config
class NotionDiaryUIFrame_Config( ui.UIFrame_Config ):
	def __init__( self, parent ):
		ui.UIFrame_Config.__init__( self, parent )

	# Handlers for UIFrame_Config events.
	def OnCancelButtonClick( self, event ):
		# TODO: Implement OnCancelButtonClick
		pass

	def OnSaveButtonClick( self, event ):
		# TODO: Implement OnSaveButtonClick
		pass


