"""Subclass of UIFrame_Setting, which is generated by wxFormBuilder."""

import wx
import ui
from NotionDiaryUIFrame_Config import NotionDiaryUIFrame_Config
import json
# Implementing UIFrame_Config
class NotionDiaryUIFrame_Config_edit( NotionDiaryUIFrame_Config ):
	def __init__( self, parent ):
		NotionDiaryUIFrame_Config.__init__( self, parent )
		try:
			with open("config", "r") as f:
				conf = json.load(f)
			self.tokenBox.SetValue(conf["token"])
			self.idBox.SetValue(conf["databaseId"])
			self.propertyBox.SetValue(conf["property"])
			self.timestampCheckBox.SetValue(conf["timestamp"])
		except FileNotFoundError:
			pass

	# Handlers for UIFrame_Config events.
	def OnCancelButtonClick( self, event ):
		# TODO: 警告メッセージ(https://docs.wxpython.org/wx.CloseEvent.html#wx-closeevent)
		self.Destroy()

	def OnSaveButtonClick( self, event ):
		# TODO: Implement OnSaveButtonClick
		token = self.tokenBox.GetValue()
		databaseId = self.idBox.GetValue()
		prop = self.propertyBox.GetValue()
		timestampCheck = self.timestampCheckBox.GetValue()
		conf = {
			"token": token,
			"databaseId": databaseId,
			"property": prop,
			"timestamp": timestampCheck
		}
		with open("config", "w") as f:
			json.dump(conf, f)
		self.Destroy()


