"""Subclass of UIFrame_main, which is generated by wxFormBuilder."""

import wx
import ui

# Implementing UIFrame_main
class NotionDiaryUIFrame_main( ui.UIFrame_main ):
	def __init__( self, parent ):
		ui.UIFrame_main.__init__( self, parent )

	# Handlers for UIFrame_main events.
	def SendOnButtonClick( self, event ):
		# TODO: Implement SendOnButtonClick
		pass

	def ConfigOnButtonClick( self, event ):
		# TODO: Implement ConfigOnButtonClick
		pass


